version: '{branch}.{build}'

configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
  - path: 'LoL Auto Login\bin\Release\LoLAutoLogin.exe'
  - path: 'Diagnostic Tool\bin\Release\lolaldiag.exe'